### PR TITLE
new 3d structures added

### LINKED ISSUE #4: Enhancement: Update The Atom Structure 2D to 3D model
Update The 2D atom structure into a 3D structure.
You can choose any library you want. But the most popular one is [three JS](https://threejs.org/).

Screenshot 2024-01-12 103456

### PR DESCRIPTION
**Pull request by AviralSingh-code**
Fixes #4

### CODE REVIEW

**Comment by psykat1116** [comment]
Look Like There is a problem with deployment. Fix It.

Screenshot 2024-01-22 215138

**Comment by psykat1116** [comment]
@AviralSingh-code What Happened? No Update?

**Comment by AviralSingh-code** [comment]
Actually the problem is that when we do a global npm install in the root folder of the project then all the dependencies that are present in the package.json file should get installed but the library that you suggested i.e three.js is present in the package.json but it doesn't get installed. npm install is what vercel does in order to deploy the project and so it is not able to find three.js declarations.

**Comment by AviralSingh-code** [comment]
I have made some changes in which I have added the declarations but the tests are still failing. As I am not able to view the deployment logs so I would appreciate it if you could let me know the error that is occurring now.

**Comment by psykat1116** [comment]
Screenshot 2024-01-25 174534

**Comment by AviralSingh-code** [comment]
Ok I am working on it !!

**Comment by AviralSingh-code** [comment]
As I can see that the tests are failing so let me deploy it from my end and when every thing is ok then I will make the changes here because I am not able to see the vercel deployment logs and I will have ask for screenshots every now and then !!

**Comment by psykat1116** [comment]
@AviralSingh-code Please Give Update

**Comment by AviralSingh-code** [comment]
I am not able to deploy it from my side but I can do this that if you could tell me the error then I would fix that and maybe in a few iterations the project will be up and going. So tell me the error that you are facing right not. Like I need the screenshot.

**Comment by psykat1116** [comment]
@AviralSingh-code 
Capture5

**Pull request closed without merging**
