### PR TITLE
Fix : The Issue Of Overflowing Unit Boxes  #3

### PR DESCRIPTION
**Pull request by Hrx4**
I fixed the issue mentioned above. please review it.

### CODE REVIEW

**Comment by psykat1116** [comment]
The Problem Is Not Fully Solved. Please Solve It Carefully. I am giving you the screenshot.

Screenshot 2024-01-12 165747

**Comment by psykat1116** [comment]
@Hrx4

**Comment by Hrx4** [comment]
i think now its ok , it is perfect in my system
Screenshot 2024-01-15 235757

**Comment by psykat1116** [comment]
@Hrx4 It Looks OK to Me. Thank You for your valuable contribution to this project.

**Pull request merged**
